client/urls.py
from django.urls import path

from . import views


app_name = "client"

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('loan-application/', views.LoanAppCreate.as_view(), name="application"),
    path('loan-list/', views.LoanAppList.as_view(), name="loan-detail"),
]

home/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "home"

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('loan-list/', views.LoanAppList.as_view(), name="loan-detail"),
    path('all-loan-list/', views.ApprovedList.as_view(), name="all-loan-detail"),
    url(r'^loan-confirm/(?P<uuid>[^/]+)/$', views.LoanConfirmationCreate.as_view(), name="loan-confirm"),
]

loan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('client/', include('client.urls')),
    path('', auth_views.LoginView.as_view(template_name='client/login.html'), name='login'),
    path('login_success/', views.login_success, name='login_success'),
    path('logout/', auth_views.LogoutView.as_view(template_name='client/logout.html'), name='logout'),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

def validate_file_extension(value):
    if not (value.name.endswith('.pdf') or value.name.endswith('.PDF')):
        raise ValidationError(u'Only pdf file is supported')

def file_size(value):
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')

class LoanApplication(models.Model):
    uid = models.UUIDField(
        unique=True,
        editable=False,
        default=uuid.uuid4,
        )
    name = models.CharField(max_length=200)
    pan_number = models.CharField(max_length=20)

    email = models.CharField(max_length=200)
    tel = models.CharField(max_length=200)

    contact_person_1 = models.CharField(max_length=200, null=True, blank=True)
    email_1 = models.CharField(max_length=200, null=True, blank=True)
    tel_1 = models.CharField(max_length=200, null=True, blank=True)

    bank_branch = models.CharField(max_length=100)
    account_no = models.CharField(max_length=30)
    ifsc_code = models.CharField(max_length=20)

    loan_amount = models.CharField(max_length=5)
    period = models.CharField(max_length=100)

    address = models.TextField(max_length=400)

    pan_doc = models.FileField(upload_to='Doc/%Y/%m/%d/', validators=[validate_file_extension, file_size])
    address_doc = models.FileField(upload_to='Doc/%Y/%m/%d/', validators=[validate_file_extension, file_size])
    cancel_cheque_doc = models.FileField(upload_to='Doc/%Y/%m/%d/', validators=[validate_file_extension, file_size])

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.OneToOneField(User, on_delete=models.PROTECT)
    approved_by = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class LoanConfirmation(models.Model):
    uid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    application_id = models.OneToOneField(LoanApplication, on_delete=models.CASCADE)
    amount = models.CharField(max_length=15)
    interest_rate = models.CharField(max_length=15)
    loan_copy = models.FileField(upload_to='AppDoc/%Y/%m/%d/', validators=[validate_file_extension, file_size])
    is_confirm = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.dwp_brn

home/models.py
from django.db import models

# Create your models here.

client/views.py
from . models import LoanApplication
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "home/dashboard.html"


class LoanAppCreate(LoginRequiredMixin, CreateView):
    model = LoanApplication
    fields = ['name', 'pan_number', 'email', 'tel', 'contact_person_1',
              'email_1', 'tel_1', 'bank_branch', 'account_no', 'ifsc_code',
              'loan_amount', 'period', 'address', 'pan_doc', 'address_doc',
              'cancel_cheque_doc']
    template_name = 'client/form_loan.html'
    success_url = reverse_lazy('client:dashboard')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class LoanAppList(LoginRequiredMixin, ListView):
    model = LoanApplication
    template_name = 'client/loanapplication_list.html'
    context_object_name = 'all_loan'

    def get_queryset(self):
        queryset = LoanApplication.objects.filter(created_by=self.request.user)
        return queryset

home/views.py
from django.contrib import messages
from django.shortcuts import redirect
from client.models import LoanApplication, LoanConfirmation
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from django.urls import reverse_lazy
from .decorators import GroupRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class DashboardView(LoginRequiredMixin, GroupRequiredMixin, TemplateView):
    template_name = "home/dashboard.html"


class LoanConfirmationCreate(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    model = LoanConfirmation
    fields = ['application_id', 'amount', 'interest_rate', 'loan_copy', 'is_confirm']
    template_name = 'home/form_loan_confirm.html'
    slug_url_kwarg = 'uuid'
    slug_field = 'uid'
    success_url = reverse_lazy('home:dashboard')

    def get_initial(self):
        loan = LoanApplication.objects.get(uid=self.kwargs['uuid'])
        initial = {
            'application_id': loan.pk,
            'amount': loan.loan_amount,
            }
        return initial

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class LoanAppList(LoginRequiredMixin, GroupRequiredMixin, ListView):
    model = LoanApplication
    template_name = 'home/loanapplication_list.html'
    context_object_name = 'all_loan'

    def get_queryset(self):
        queryset = LoanApplication.objects.all()
        return queryset

class ApprovedList(LoginRequiredMixin, GroupRequiredMixin, ListView):
    model = LoanApplication
    template_name = 'home/loanapproved_list.html'
    context_object_name = 'all_loan'

    def get_queryset(self):
        queryset = LoanApplication.objects.filter(pk__in=LoanConfirmation.objects.all())
        return queryset


def login_success(request):

    if request.user.groups.filter(name="home").exists():
        messages.success(request, f'You have been signed in successfully!')
        return redirect("home:dashboard")
    else:
        messages.success(request, f'You have been signed in successfully!')
        return redirect("client:dashboard")

client/templates/client/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'client:dashboard' %}">ABC Bank</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'client:application' %}">Loan Application</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'client:loan-detail' %}">Application Status</a>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="#"><span class="fas fa-user"></span>&nbsp;<strong>{{request.user.username}}</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}"><span class="fas fa-sign-out-alt"></span>&nbsp;<strong>Log Out</strong></a>
      </li>
    </ul>
  </div>
</nav>
<br><br>
    {% block body %}

    {% endblock %}
<br><br>
  </body>
</html>

client/templates/client/dashboard.html
{% extends 'client/base.html' %}
{% block title %}Client | Dashboard{% endblock %}
{% block body %}

{% endblock %}

client/templates/client/form_loan.html
{% extends 'client/base.html' %}
{% block title %}Loan Application{% endblock %}
{% block body %}
<div class="container">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Loan Application</h6>
    </div>
    <div class="card-body">
      <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'client/form_template.html' %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
  $("input").addClass("form-control");
  $("textarea").addClass("form-control");
</script>
{% endblock %}

client/templates/client/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

client/templates/client/loanapplication_list.html
{% extends 'client/base.html' %}
{% block title %}Application Status{% endblock %}
{% block body %}
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Application Status</h6>
    </div>
    <div class="card-body">
      {% if all_loan %}
      <div class="table-responsive">
        <table class="table table-striped mb-4">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Date</th>
              <th>Amount</th>
              <th>Period</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for item in all_loan %}
            <tr>
              <td>{{ item.pk }}</td>
              <td>{{ item.name }}</td>
              <td>{{ item.created_at }}</td>
              <td>{{ item.loan_amount }}</td>
              <td>{{ item.period }}</td>
              <td>{% if item.loanconfirmation %} Approved {% else %} Pending {% endif %}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <br><br><br>
      <div style="text-align:center;">
        <h3>No Loan Application Available</h3>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

client/templates/client/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <style media="screen">
    .container {
      background-color: white;
      padding: 20px;
      position: absolute;
      top: 50%;
      left: 50%;
      -moz-transform: translateX(-50%) translateY(-50%);
      -webkit-transform: translateX(-50%) translateY(-50%);
      transform: translateX(-50%) translateY(-50%);
    }
    </style>
    <div class="container">
      <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'client/form_template.html' %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

client/templates/client/logout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Logout</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <style media="screen">
    .container {
      background-color: white;
      padding: 20px;
      position: absolute;
      top: 50%;
      left: 50%;
      -moz-transform: translateX(-50%) translateY(-50%);
      -webkit-transform: translateX(-50%) translateY(-50%);
      transform: translateX(-50%) translateY(-50%);
    }
    </style>
    <div class="container">
      <h2>You have been logged out</h2>
      <div class="border-top pt-3">
        <small class="text-muted">
          <a class="ml-2" href="{% url 'login' %}">Log In Again</a>
        </small>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home:dashboard' %}">ABC Bank</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:loan-detail'%}">All Application <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:all-loan-detail' %}">Approved Application</a>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="#"><span class="fas fa-user"></span>&nbsp;<strong>{{request.user.username}}</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}"><span class="fas fa-sign-out-alt"></span>&nbsp;<strong>Log Out</strong></a>
      </li>
    </ul>
  </div>
</nav>
<br><br>
    {% block body %}

    {% endblock %}
<br><br>
  </body>
</html>

home/templates/home/dashboard.html
{% extends 'home/base.html' %}
{% block title %}Home | Dashboard{% endblock %}
{% block body %}

{% endblock %}

home/templates/home/form_loan_confirm.html
{% extends 'home/base.html' %}
{% block title %}Loan Approve{% endblock %}
{% block body %}
<div class="container">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Loan Approve</h6>
    </div>
    <div class="card-body">
      <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'client/form_template.html' %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
  $("input").addClass("form-control");
  $("textarea").addClass("form-control");
</script>
{% endblock %}

home/templates/home/loanapplication_list.html
{% extends 'home/base.html' %}
{% block title %}All Application{% endblock %}
{% block body %}
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">All Application</h6>
    </div>
    <div class="card-body">
      {% if all_loan %}
      <div class="table-responsive">
        <table class="table table-striped mb-4">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Date</th>
              <th>Amount</th>
              <th>Period</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for item in all_loan %}
            <tr>
              <td>{{ item.pk }}</td>
              <td>{{ item.name }}</td>
              <td>{{ item.created_at }}</td>
              <td>{{ item.loan_amount }}</td>
              <td>{{ item.period }}</td>
              <td>{% if item.loanconfirmation %} Approved {% else %} <a href="{% url 'home:loan-confirm' item.uid %}">Confirm</a> {% endif %}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <br><br><br>
      <div style="text-align:center;">
        <h3>No Loan Application Available</h3>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/loanapproved_list.html
{% extends 'home/base.html' %}
{% block title %}All Application{% endblock %}
{% block body %}
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Approved Loan</h6>
    </div>
    <div class="card-body">
      {% if all_loan %}
      <div class="table-responsive">
        <table class="table table-striped mb-4">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Date</th>
              <th>Amount</th>
              <th>Period</th>
              <th>Approved On</th>
            </tr>
          </thead>
          <tbody>
            {% for item in all_loan %}
            <tr>
              <td>{{ item.pk }}</td>
              <td>{{ item.name }}</td>
              <td>{{ item.created_at }}</td>
              <td>{{ item.loan_amount }}</td>
              <td>{{ item.period }}</td>
              <td>{{ item.updated_at}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <br><br><br>
      <div style="text-align:center;">
        <h3>No Loan Application Available</h3>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}